export const frameAttributes: string[] = []
export const gestureAttributes: string[] = []
export const paletteAttributes: string[] = []
export const backgroundAttributes: string[] = []
export const periodAttributes: string[] = []
