export const context = [
  {
    name: 'Action',
    attributes: [
      'Assembling a team of unlikely allies',
      'Blocking the doorway against oncoming foes',
      'Breaking through enemy lines',
      'Calling upon ancestral spirits',
      'Carving a path through obstructed terrain',
      'Casting a spell of enchantment',
      'Casting a spell of illusion',
      'Channeling inner serenity',
      'Charging into battle',
      'Climbing a cliff',
      'Commanding an army',
      'Constructing a trap',
      'Cooking a simple meal',
      'Cracking a complex safe',
      'Crafting an intricate potion',
      'Crossing a portal to another realm',
      'Crossing a rickety rope bridge',
      'Crouching before an altar',
      'Dancing',
      'Defending a narrow pass',
      'Deflecting a barrage of projectiles',
      'Delivering a speech',
      'Disarming a trap',
      'Discovering a hidden treasure trove',
      'Dodge rolling an attack',
      'Dodging lethal strikes',
      'Enduring an arrow wound',
      'Erupting in uncontrollable laughter',
      'Escaping pursuers',
      'Escaping a collapsing chamber',
      'Escaping the clutches of quicksand',
      'Examining an ancient artifact',
      'Facing a mighty monster',
      'Fending off a horde of foes',
      'Gathering rare and exotic ingredients',
      'Getting across a magical barrier',
      'Getting free from being tied up',
      'Getting trapped in a enchanted prison',
      'Guarding an entrance',
      'Guiding a lost soul to rest',
      'Healing wounds with a magical potion',
      'Holding a cursed item',
      'Igniting a dynamite fuse',
      'Journeying through an ancient forest',
      'Launching an ambush',
      'Looting a dead body',
      'Navigating a maze',
      'Patrolling between buildings',
      'Peeing by the roadside',
      'Rescuing a companion from quicksand',
      'Resting next to a campfire',
      'Reviving a magical entity',
      'Roaring a battle cry',
      'Seeking hidden knowledge in a library',
      'Seeking hidden passages',
      'Sharpening a blade',
      'Sneaking through shadows',
      'Standing sentinel',
      'Summonning a magical servant',
      'Surviving an arena battle',
      'Tracking an elusive quarry',
      'Unleashing a flurry of kicks',
      'Unleashing a powerful spell',
      'Unraveling a mystery',
      'Walking along a path',
      'Weaving a protective barrier',
    ],
  },
]
export const frameAttributes: string[] = [
  'Gros plan',
  'Plan poitrine',
  'Plan taille',
  'Plan américain',
  'Plan italien',
  'Plan moyen',
  'Plan large',
]
export const paletteAttributes: string[] = []
export const backgroundAttributes: string[] = []
export const periodAttributes: string[] = []
