export const coreTraits = [
  {
    name: 'Race',
    attributes: [
      'Human',
      'Elf',
      'Orc',
      'Goblin',
      'Dragon',
      'Gnome',
      'Troll',
      'Demon',
      'Werewolf',
      'Wererat',
      'Werefox',
      'Wereboar',
      'Centaur',
      'Vampire',
      'Elemental',
      'Ghost',
      'Undead',
      'Dwarf',
      'Fairy',
      'Succubus',
      'Angel',
      'Giant',
      'Gorgon',
      'Faun',
    ],
  },
  {
    name: 'Class',
    attributes: [
      'Warrior',
      'Mage',
      'Archer',
      'Thief',
      'Priest',
      'Engineer',
      'Alchemist',
      'Monster hunter',
      'Necromancer',
      'Bard',
      'Paladin',
      'Ranger',
      'Assassin',
      'Druid',
      'Barbarian',
      'Knight',
      'Cleric',
      'Beastmaster',
    ],
  },
]
