export const equipments = [
  {
    name: 'Weapon',
    dimensions: 'md:row-start-1 md:row-end-6',
    icon: 'weapon',
    color: 'F7E5E5',
    attributes: [
      'Ankus',
      'Arquebus',
      'Axe',
      'Axe-knife',
      'Basket-hilted sword',
      'Berdiche',
      'Bolas',
      'Boomerang',
      'Bow',
      'Broom',
      'Cane',
      'Cannon',
      'Censer',
      'Cestus',
      'Chain whip',
      'Chakram',
      'Claws',
      'Cleaver',
      'Club',
      'Combined gun weapon',
      'Crescent moon knives',
      'Crossbow',
      'Crucifix',
      'Dagger',
      'Dagger-axe',
      'Dao',
      'Falchion',
      'Fan',
      'Flail',
      'Gauntlet sword',
      'Glaive',
      'Greatsword',
      'Grimoire',
      'Guisarme',
      'Gun',
      "Gunner's linstock",
      'Halberd',
      'Hook',
      'Hook sword',
      'Javelin',
      'Kama',
      'Katana',
      'Katar',
      'Khopesh',
      'Knife',
      'Knuckle dusters',
      'Kriss',
      'Longsword',
      'Mace',
      'Machete',
      'Magic skull',
      'Magic wand',
      'Messer',
      'Meteor hammer',
      'Military fork',
      'Net',
      'Nunchakus',
      'Parrying dagger',
      'Pickaxe',
      'Pistol',
      'Pitchfork',
      'Poleaxe',
      'Power blade',
      'Punch weapon',
      'Rapier',
      'Ritual staff',
      'Rope dart',
      'Sabre',
      'Sai',
      'Saw',
      'Sceptre',
      'Scissors',
      'Scroll',
      'Scythe',
      'Shortsword',
      'Shovel',
      'Shuriken',
      'Sickle',
      'Slingshot',
      'Spear', // 'Pike',
      'Staff',
      'Sword',
      'Throwing axe',
      'Throwing knives',
      'Tonfa',
      'Vajra',
      'Voulge',
      'Warhammer',
      'War skirt',
      'Whip',
    ],
  },
  {
    name: 'Head',
    dimensions: 'md:row-start-1 md:row-end-3',
    icon: 'head',
    color: 'E6F3DD',
    attributes: [
      'Ancient helmet',
      'Balaclava',
      'Barbute',
      'Bascinet',
      'Beanie',
      'Bob',
      'Bonnet',
      'Bubble helmet',
      'Burgonet',
      'Bycocket',
      'Cap',
      'Cervelliere',
      'Circlet',
      'Close helmet',
      'Coif',
      'Crown',
      'Crown of thorns',
      'Crusader helmet',
      'Diving helmet',
      'Escoffion',
      'Face scarf',
      'Feather headdress',
      'Fez',
      'Fur hat',
      'Gladiator helmet',
      'Great helm',
      'Hair jewelry',
      'Hairnet',
      'Halo crown',
      'Head load',
      'Headband',
      'Headdress',
      'Headscarf',
      'Hennin',
      'Hood',
      'Horns',
      'Janissary cap',
      'Kabuto',
      'Kettle hat',
      'Lamellar helmet',
      'Mail coif',
      'Mask',
      'Mask helmet',
      'Mitre',
      'Pirate hat',
      'Quilted hood',
      'Roundlet',
      'Sallet',
      'Skull',
      'Straw hat',
      'Turban',
      'Turban helmet',
      'Vegetal coif',
      'Veil',
      'Wide-brimmed hat',
      'Witch hat',
    ],
  },
  {
    name: 'Neck',
    dimensions: 'md:row-start-1 md:row-end-3',
    icon: 'jewels',
    color: 'E6F7EB',
    attributes: [
      'Amulet',
      'Bead necklace',
      'Bevor',
      'Bone necklace',
      'Choker',
      'Collar',
      'Earings',
      'Eye patch',
      'Glasses',
      'Goggles',
      'Gorget',
      'Lip plate',
      'Mail collar',
      'Monocle',
      'Neck corset',
      'Neck rings',
      'Necklace',
      'Padded gorget',
      'Rosary',
      'Ruff',
      'Scarf',
      'Spiked collar',
      'Torc',
      'Whisk collar',
    ],
  },
  {
    name: 'Chest',
    dimensions: 'md:row-start-3 md:row-end-6',
    icon: 'body',
    color: 'D9F5E6',
    attributes: [
      'Bodice',
      'Body jewellery',
      'Bodysuit',
      'Bolero jacket',
      'Bra',
      'Brigandine',
      'Catsuit',
      'Chainmail shirt',
      'Coat',
      'Corset',
      'Corset dress',
      'Crop top',
      'Cuirass', // 'Breastplate', 'Plackart',
      'Doublet',
      'Dress',
      'Fishnet top',
      'Fur coat',
      'Gambeson',
      'Harness',
      'Jack of plate',
      'Jacket',
      'Jumpsuit',
      'Kimono',
      'Kirtle',
      'Lamellar armor',
      'Laminar armor',
      'Leather armor',
      'Mantle',
      'Mini-dress',
      'Mirror armor',
      'Pasties',
      'Poet shirt',
      'Poncho',
      'Rags',
      'Priest robe',
      'Scale armor',
      'Sheer gown',
      'Shirt',
      'Skull armor',
      'Sleeveless shirt',
      'Straight-jacket',
      'Surcoat',
      'Sweater',
      'Tailcoat',
      'Toga',
      'Tunic',
      'Vest',
      'Wedding gown',
    ],
  },
  {
    name: 'Shoulders',
    dimensions: 'md:row-start-3 md:row-end-8',
    icon: 'back',
    color: 'E6E6F7',
    attributes: [
      'Baby carrier',
      'Backpack',
      'Cape',
      'Capelet',
      'Cloak',
      'Epaulets',
      'Feather cape',
      'Fur cape',
      'Jetpack',
      'Jousting shield',
      'Pauldrons',
      'Roundels',
      'Shawl',
      'Shrug',
      'Single-spaulder',
      'Stole',
      'Straw cape',
      'Tabard',
      'Wings',
    ],
  },
  {
    name: 'Hands',
    dimensions: 'md:row-start-6 md:row-end-8',
    icon: 'hands',
    color: 'F7F2E6',
    attributes: [
      'Arm guards',
      'Arm harness',
      'Arm wraps',
      'Bracelets',
      'Bracers',
      'Fake cuffs',
      'Fingerless gloves',
      'Fur mittens',
      'Gloves', // 'Silk gloves'
      'Handcuffs',
      'Leather gauntlets',
      'Long gloves',
      'Mail gloves',
      'Mesh gloves',
      'Mittens',
      'Padded gauntlets',
      'Plate arms',
      'Prosthetic arm',
      'Ring',
      'Sleeves',
      'Steel gauntlets',
      'Vambraces',
      'Wrist warmers',
    ],
  },
  {
    name: 'Hips',
    dimensions: 'md:row-start-6 md:row-end-8',
    icon: 'belt',
    color: 'E1EAF5',
    attributes: [
      'Apron',
      'Baldric',
      'Chain belt',
      'Corset-belt',
      'Evening belt',
      'Faulds',
      'Fur belt',
      'Hip scarf',
      'Holster',
      'Leather belt',
      'Leg harness',
      'Mail skirt',
      'Military belt',
      'Obi',
      'Rope belt',
      'Scabbard',
      'Studded belt',
      'Suspenders',
      'Tribal belt',
      'Utility belt',
      'Waist sash',
      // 'Hip pouch',
      // 'Brigandine skirt',
      // 'Leather scale skirt',
      // 'Padded skirt',
      // 'Steel scale skirt'
    ],
  },
  {
    name: 'Accessories',
    dimensions: 'md:row-start-8 md:row-end-13',
    icon: 'accessories',
    color: 'F3F7E6',
    attributes: [
      'Banner',
      'Barrel',
      'Basket',
      'Bell',
      'Booze',
      'Bucket',
      'Calipers',
      'Canteen',
      'Chains',
      'Chalice',
      'Chest',
      'Crucifix',
      'Divinatory pendulum',
      'Doll',
      'Drinking horn',
      'Fairy dust',
      'First aid kit',
      'Gourd',
      'Grapplin hook',
      'Grimoire',
      'Gunpowder',
      'Hand mirror',
      'Keyring',
      'Kitchenware',
      'Lamp',
      'Medicinal herbs',
      'Musical instrument',
      'Pavise',
      'Pipe',
      'Pharmacist kit',
      'Pocket watch',
      'Potion',
      'Pouch',
      'Purse',
      'Quiver',
      'Reliquary',
      'Rope',
      'Rosary',
      'Satchel',
      'Scroll',
      'Shield',
      'Shoulder bag',
      'Skull',
      'Torch',
      'Trap',
      'Trinket box',
      'Umbrella',
      'Vampire hunting kit',
      'Voodoo doll',
    ],
  },
  {
    name: 'Legs',
    dimensions: 'md:row-start-8 md:row-end-11',
    icon: 'legs',
    color: 'F4DFED',
    attributes: [
      'Breeches',
      'Chausses',
      'Hakama',
      'Harem pants',
      'Hosiery',
      'Knee-high socks',
      'Leg jewellery',
      'Leggings',
      'Loincloth',
      'Mail chausses',
      'Mini-skirt',
      'Overalls',
      'Padded chausses',
      'Pants', // 'Leather trousers', 'Cargo pants', 'Fur pants', etc...
      'Plate greaves',
      'Poleyns',
      'Prosthetic leg',
      'Shorts',
      'Skirt',
      'Underwear',
      'War skirt',
    ],
  },
  // {
  //   name: 'Pet',
  //   dimensions: 'md:row-start-8 md:row-end-13',
  //   icon: 'pet',
  //   color: 'F7E6E7',
  //   attributes: [
  //     '-',
  //     'Baby wyvern',
  //     'Cat',
  //     'Centipede',
  //     'Crow',
  //     'Dog',
  //     'Eagle',
  //     'Elemental',
  //     'Fairy',
  //     'Feline',
  //     'Flesh homunculus',
  //     'Ghost',
  //     'Giant rat',
  //     'Giant Spider',
  //     'Goat',
  //     'Goblin',
  //     'Griffon',
  //     'Gryphon',
  //     'Horse',
  //     'Imp',
  //     'Kobold',
  //     'Living puppet',
  //     'Living puppet',
  //     'Lizard',
  //     'Mini-dragon',
  //     'Ostrich',
  //     'Owl',
  //     'Parrot',
  //     'Pegasus',
  //     'Phoenix',
  //     'Serpent',
  //     'Swarm of rats',
  //     'Tiger',
  //     'Unicorn',
  //     'Warg',
  //     'Wolf',
  //     'Zombie',
  //   ],
  // },
  {
    name: 'Feet',
    dimensions: 'md:row-start-11 md:row-end-13',
    icon: 'feet',
    color: 'F5EFDF',
    attributes: [
      'Anklets',
      'Clogs',
      'Flip-flops',
      'Fur boots',
      'Geta',
      'High boots',
      'High heels',
      'Leather boots',
      'Leather greaves',
      'Leather shoes',
      'Lotus shoes',
      'Moccassins',
      'Pattens',
      'Sabatons',
      'Sandals',
      'Thigh-high boots',
      'Slippers',
    ],
  },
]
