export const equipments = [
  {
    name: 'Weapon',
    dimensions: 'md:row-start-1 md:row-end-6',
    icon: 'weapon',
    color: 'F7E5E5',
    attributes: [
      '-',
      'Ankus',
      'Arquebus',
      'Axe-knife',
      'Axe',
      'Basket-hilted sword',
      'Berdiche',
      'Bolas',
      'Boomerang',
      'Bow',
      'Broom',
      'Cane',
      'Cannon',
      'Censer',
      'Cestus',
      'Chain whip',
      'Chakram',
      'Claws',
      'Cleaver',
      'Club',
      'Combined gun weapon',
      'Crescent moon knives',
      'Crossbow',
      'Dagger-axe',
      'Dagger',
      'Dao',
      'Falchion',
      'Fan',
      'Flail',
      'Gauntlet sword',
      'Glaive',
      'Greatsword',
      'Grimoire',
      'Guisarme',
      'Gun',
      "Gunner's linstock",
      'Halberd',
      'Hammer',
      'Hook sword',
      'Javelin',
      'Kama',
      'Katana',
      'Katar',
      'Khopesh',
      'Knife',
      'Knuckle dusters',
      'Kriss',
      'Lamp',
      'Longsword',
      'Mace',
      'Machete',
      'Magic skull',
      'Magic wand',
      'Messer',
      'Meteor hammer',
      'Military fork',
      'Net',
      'Nunchakus',
      'Parrying dagger',
      'Pavise',
      'Pickaxe',
      'Pike',
      'Pistol',
      'Pitchfork',
      'Poleaxe',
      'Power blade',
      'Punch weapon',
      'Rapier',
      'Ritual staff',
      'Rope dart',
      'Sabre',
      'Sai',
      'Saw',
      'Sceptre',
      'Scissors',
      'Scroll',
      'Scythe',
      'Shield',
      'Shortsword',
      'Shovel',
      'Shuriken',
      'Sickle',
      'Slingshot',
      'Spear',
      'Staff',
      'Sword',
      'Throwing axe',
      'Throwing knives',
      'Tonfa',
      'Torch',
      'Umbrella',
      'Vajra',
      'Voulge',
      'Warhammer',
      'Whip',
    ],
  },
  {
    name: 'Head',
    dimensions: 'md:row-start-1 md:row-end-3',
    icon: 'head',
    color: 'E6F3DD',
    attributes: [
      '-',
      'Balaclava',
      'Beanie',
      'Beret',
      'Brimm hat',
      'Cap',
      'Circlet',
      'Coif',
      'Crown of thorns',
      'Crown',
      'Diving helmet',
      'Earings',
      'Face scarf',
      'Feather headress',
      'Fur hat',
      'Hair jewelry',
      'Hairnet',
      'Halo crown',
      'Hat',
      'Head load',
      'Headband',
      'Headress',
      'Headscarf',
      'Helmet',
      'Hood',
      'Horns',
      'Kabuto',
      'Lip plate',
      'Mail coif',
      'Mask',
      'Mitre',
      'Quilted hood',
      'Roundlet',
      'Skull',
      'Straw hat',
      'Tricorn hat',
      'Turban',
      'Vegetal coif',
      'Veil',
      'Witch hat',
    ],
  },
  {
    name: 'Neck',
    dimensions: 'md:row-start-1 md:row-end-3',
    icon: 'jewels',
    color: 'E6F7EB',
    attributes: [
      '-',
      'Bead necklace',
      'Bevor',
      'Bone necklace',
      'Choker',
      'Collar',
      'Gorget',
      'Mail collar',
      'Neck corset',
      'Neck rings',
      'Necklace',
      'Padded gorget',
      'Pendant',
      'Ruff',
      'Scarf',
      'Spiked collar',
      'Stole',
      'Torc',
    ],
  },
  {
    name: 'Body',
    dimensions: 'md:row-start-3 md:row-end-6',
    icon: 'body',
    color: 'D9F5E6',
    attributes: [
      '-',
      'Bodice',
      'Body jewellery',
      'Bodysuit',
      'Bra',
      'Brigandine',
      'Catsuit',
      'Chainmail shirt',
      'Coat',
      'Corset dress',
      'Corset',
      'Crop top',
      'Cuirass',
      'Doublet',
      'Dress',
      'Fishnet top',
      'Fur coat',
      'Gambeson',
      'Harness',
      'Jack of plate',
      'Jacket',
      'Jumpsuit',
      'Kimono',
      'Kirtle',
      'Lamellar armor',
      'Laminar armor',
      'Leather armor',
      'Mantle',
      'Mini-dress',
      'Mirror armor',
      'Pasties',
      'Poet shirt',
      'Poncho',
      'Rags',
      'Rib cage',
      'Robe',
      'Scale armor',
      'Sheer gown',
      'Shirt',
      'Sleeveless shirt',
      'Straight-jacket',
      'Surcoat',
      'Sweater',
      'Tabard',
      'Tailcoat',
      'Toga',
      'Tunic',
      'Vest',
      'Wedding gown',
    ],
  },
  {
    name: 'Shoulders',
    dimensions: 'md:row-start-3 md:row-end-8',
    icon: 'back',
    color: 'E6E6F7',
    attributes: [
      '-',
      'Arm armor',
      'Arm harness',
      'Bolero jacket',
      'Cape',
      'Capelet',
      'Cloak',
      'Epaulets',
      'Feather cape',
      'Fur cape',
      'Jetpack',
      'Jousting shield',
      'Pauldrons',
      'Roundels',
      'Shawl',
      'Shrug',
      'Single-spaulder',
      'Sleeves',
      'Straw cape',
      'Whisk collar',
      'Wings',
    ],
  },
  {
    name: 'Hands',
    dimensions: 'md:row-start-6 md:row-end-8',
    icon: 'hands',
    color: 'F7F2E6',
    attributes: [
      '-',
      'Arm wraps',
      'Bracelets',
      'Bracers',
      'Fake cuffs',
      'Fingerless gloves',
      'Fur mittens',
      'Gloves',
      'Leather gauntlets',
      'Long gloves',
      'Mail gloves',
      'Mesh gloves',
      'Mittens',
      'Padded gauntlets',
      'Plate arms',
      'Prosthetic arm',
      'Ring',
      'Steel gauntlets',
      'Vambraces',
      'Wrist warmers',
    ],
  },
  {
    name: 'Hips',
    dimensions: 'md:row-start-6 md:row-end-8',
    icon: 'hips',
    color: 'E1EAF5',
    attributes: [
      '-',
      'Apron',
      'Chain belt',
      'Corset-belt',
      'Evening belt',
      'Faulds',
      'Fur belt',
      'Hip scarf',
      'Leather belt',
      'Loincloth',
      'Mail skirt',
      'Military belt',
      'Obi',
      'Rope belt',
      'Studded belt',
      'Tribal belt',
      'Utility belt',
      'Waist sash',
    ],
  },
  {
    name: 'Accessories',
    dimensions: 'md:row-start-8 md:row-end-13',
    icon: 'accessories',
    color: 'F3F7E6',
    attributes: [
      '-',
      'Baby carrier',
      'Backpack',
      'Baldric',
      'Banner',
      'Barrel',
      'Basket',
      'Beer mug',
      'Bell',
      'Booze',
      'Bucket',
      'Calipers',
      'Canteen',
      'Censer',
      'Chains',
      'Chalice',
      'Chest',
      'Crucifix',
      'Divinatory pendulum',
      'Doll',
      'Drinking horn',
      'Eye patch',
      'Fairy dust',
      'Glasses',
      'Goggles',
      'Gourd',
      'Grapplin hook',
      'Grimoire',
      'Gunpowder',
      'Hand mirror',
      'Handcuffs',
      'Holster',
      'Keyring',
      'Kitchenware',
      'Lamp',
      'Magic skull',
      'Medical tools',
      'Medicinal herbs',
      'Monocle',
      'Musical instrument',
      'Pipe',
      'Pocket watch',
      'Potion',
      'Pouch',
      'Purse',
      'Quiver',
      'Reliquary',
      'Rope',
      'Rosary',
      'Satchel',
      'Saw',
      'Scabbard',
      'Scissors',
      'Scroll',
      'Shoulder bag',
      'Skull',
      'Suspenders',
      'Trap',
      'Trinket box',
      'Voodoo doll',
    ],
  },
  {
    name: 'Legs',
    dimensions: 'md:row-start-8 md:row-end-11',
    icon: 'legs',
    color: 'F4DFED',
    attributes: [
      '-',
      'Breeches',
      'Chausses',
      'Hakama',
      'Harem pants',
      'Hosiery',
      'Knee-high socks',
      'Leather greaves',
      'Leg harness',
      'Leg jewellery',
      'Leg wraps',
      'Leggings',
      'Mail chausses',
      'Mini-skirt',
      'Overalls',
      'Padded chausses',
      'Pants',
      'Plate greaves',
      'Poleyns',
      'Shorts',
      'Skirt',
      'Underwear',
      'War skit',
    ],
  },
  // {
  //   name: 'Pet',
  //   dimensions: 'md:row-start-8 md:row-end-13',
  //   icon: 'pet',
  //   color: 'F7E6E7',
  //   attributes: [
  //     '-',
  //     'Baby wyvern',
  //     'Cat',
  //     'Centipede',
  //     'Crow',
  //     'Dog',
  //     'Donkey',
  //     'Eagle',
  //     'Elemental',
  //     'Fairy',
  //     'Feline',
  //     'Fish',
  //     'Flesh homunculus',
  //     'Ghost',
  //     'Giant rat',
  //     'Giant Spider',
  //     'Goat',
  //     'Goblin',
  //     'Griffon',
  //     'Gryphon',
  //     'Horse',
  //     'Imp',
  //     'Kobold',
  //     'Living puppet',
  //     'Lizard',
  //     'Mini-dragon',
  //     'Ostrich',
  //     'Owl',
  //     'Parrot',
  //     'Pegasus',
  //     'Phoenix',
  //     'Serpent',
  //     'Swarm of rats',
  //     'Tiger',
  //     'Unicorn',
  //     'Warg',
  //     'Wolf',
  //     'Zombie',
  //   ],
  // },
  {
    name: 'Feet',
    dimensions: 'md:row-start-11 md:row-end-13',
    icon: 'feet',
    color: 'F5EFDF',
    attributes: [
      '-',
      'Anklets',
      'Boots',
      'Clogs',
      'Face scarf',
      'Flip-flops',
      'Fur boots',
      'Geta',
      'High boots',
      'High heels',
      'Leather shoes',
      'Lotus shoes',
      'Moccasins',
      'Pattens',
      'Prosthetic leg',
      'Sabatons',
      'Sandals',
      'Slippers',
      'Thigh-high boots',
    ],
  },
]
