export const equipments = [
  {
    name: 'Head',
    icon: 'head',
    color: '#E6F3DD',
    attributes: [
      'Chapeau',
      'Casquette',
      'Berêt',
      'Casque',
      'Couronne',
      'Bandana',
      'Tiare',
      '',
    ],
  },
  {
    name: 'Hands',
    icon: 'hands',
    color: '#F7F2E6',
    attributes: ['Gants en cuir', 'Bracelets', 'Mains nues', 'Gantelets'],
  },
  {
    name: 'Weapon',
    icon: 'weapon',
    color: '#F7E5E5',
    attributes: [
      'Épée longue',
      'Épée courte',
      'Dague',
      'Sabre',
      'Cane',
      'Baton',
      'Lance',
      'Baguette/Baton magique',
      'Griffes',
      'Grimoire',
      'Fléau',
      'Bourse',
      'Arc et flèches',
    ],
  },
  {
    name: 'Body',
    icon: 'body',
    color: '#D9F5E6',
    attributes: [
      'Plastron',
      'Grigandine',
      'Veste',
      'Torse nu',
      'Haillons',
      'Chemise',
      'Costard',
      'Robe',
      'Manteau',
    ],
  },
  {
    name: 'Back',
    icon: 'back',
    color: '#E6E6F7',
    attributes: [
      'Cape',
      'Capuche',
      'Écharpe',
      'Sac à dos',
      'Sac en bandoulière',
      'Fourrure',
      'Bouclier',
    ],
  },
  {
    name: 'Belt',
    icon: 'belt',
    color: '#E1EAF5',
    attributes: [
      'Fourreau',
      'Ceinturon',
      'Plusieurs ceintures',
      'Corde',
      'Pansière',
    ],
  },
  {
    name: 'Legs',
    icon: 'legs',
    color: '#F4DFED',
    attributes: [
      'Jupe',
      'Pantalon droit',
      'Baggy',
      'Collants',
      'Jogging',
      'Short',
      'Slip',
    ],
  },
  {
    name: 'Feet',
    icon: 'feet',
    color: '#F5EFDF',
    attributes: [
      'Bottes',
      'Chaussures',
      'Talons',
      'Pieds nus',
      'Cuissardes',
      'Solerets',
    ],
  },
  {
    name: 'Accessories',
    icon: 'accessories',
    color: '#F3F7E6',
    attributes: ['Fioles', 'Bourse', "Arme d'apparât", 'Grimoire', 'Sac'],
  },
  {
    name: 'Jewels',
    icon: 'jewels',
    color: '#E6F7EB',
    attributes: [
      'Bagues',
      'Pendentif',
      'Chaîne',
      'Piercings',
      'Montre à gousset',
      'Bracelets',
      'Masque',
      'Lunettes',
    ],
  },
  {
    name: 'Pet',
    icon: 'pet',
    color: '#F7E6E7',
    attributes: [
      'Nuée de rats',
      'Araignée géante',
      'Chien',
      'Loup',
      'Félin',
      'Cheval',
      'Zombie',
      'Lézard',
      'Gobelin',
      'Chat',
      'Serpent',
      'Élémentaire',
      'Mini-dragon',
    ],
  },
]
