export const physicalTraits = [
  {
    name: 'Gender',
    attributes: ['Male', 'Female', 'Queer'],
  },
  {
    name: 'Age',
    attributes: ['Child', 'Young', 'Adult', 'Mature', 'Elderly'],
  },
  {
    name: 'Physique',
    attributes: [
      'Tall and thin',
      'Colossus',
      'Dwarf',
      'Hunchback',
      'Muscular',
      'Thin',
      'Muscular',
      'Strong',
      'Bodybuilder',
      'Fit',
      'Obese',
      'Fat',
      'Overweight',
    ],
  },
  {
    name: 'Hairstyle',
    attributes: [
      'Bald',
      'Long hair',
      'Very long hair',
      'Short hair',
      'Balding',
    ],
  },
  {
    name: 'Particular feature',
    attributes: [
      'Big teeth',
      'Big eyes',
      'Big lips',
      'Square chin',
      'No neck',
      'One-armed',
      'One-legged',
      'Missing eye',
      'Big nose',
      'Beard',
      'Mustache',
      'Bushy eyebrows',
      'Hairy',
      'Tattoos',
      'Scars',
      'Hairy',
      'Wrinkles',
      'Freckles',
    ],
  },
  {
    name: 'Temperament',
    attributes: [
      'Shy',
      'Proud',
      'Intellectual',
      'Idiot',
      'Angry',
      'Sad',
      'Scared',
      'Courageous',
      'Enigmatic',
      'Noble',
      'Cunning',
      'Mad',
    ],
  },
]
