export const physicalTraits = [
  {
    name: 'Gender',
    attributes: ['Female', 'Male', 'Non-binary'],
  },
  {
    name: 'Age',
    attributes: [
      'Adult',
      'Centenarian',
      'Child',
      'Elderly',
      'Mature',
      'Teenager',
      'Young',
    ],
  },
  {
    name: 'Physique',
    attributes: [
      'Average',
      'Bodybuilder',
      'Chubby',
      'Colossus',
      'Dwarf',
      'Fat',
      'Fit',
      'Hunchback',
      'Muscular',
      'Muscular',
      'Obese',
      'Paunchy',
      'Portly',
      'Slender',
      'Stocky',
      'Strong',
      'Tall',
      'Thin',
    ],
  },
  {
    name: 'Hairstyle',
    attributes: [
      'Afro',
      'Bald',
      'Balding',
      'Braids',
      'Buzz cut',
      'Curly',
      'Dreadlocks',
      'Long hair',
      'Messy',
      'Mullet',
      'Ponytail',
      'Short hair',
      'Tonsure',
      'Very long hair',
      'Wavy',
    ],
  },
  {
    name: 'Particular feature',
    attributes: [
      '-',
      'Beard',
      'Big eyes',
      'Big lips',
      'Big nose',
      'Big teeth',
      'Bushy eyebrows',
      'Earrings',
      'Fangs',
      'Freckles',
      'Glasses',
      'Hairy',
      'Heterochromia',
      'Missing eye',
      'Mustache',
      'No neck',
      'Nose ring',
      'One-armed',
      'One-legged',
      'Piercings',
      'Scars',
      'Square chin',
      'Tattoos',
      'Wrinkles',
    ],
  },
  {
    name: 'Temperament',
    attributes: [
      'Angry',
      'Anxious',
      'Calm',
      'Confident',
      'Courageous',
      'Cunning',
      'Enigmatic',
      'Idiot',
      'Intellectual',
      'Mad',
      'Noble',
      'Proud',
      'Sad',
      'Scared',
      'Shy',
    ],
  },
]
