export const physicalTraits = [
  {
    name: 'Genre',
    attributes: ['Mâle', 'Femelle', 'Queer'],
  },
  {
    name: 'Âge',
    attributes: ['Enfant', 'Jeune', 'Adulte', 'Mûr', 'Vieux'],
  },
  {
    name: 'Morphologie',
    attributes: [
      'Grand maigre',
      'Colosse',
      'Nain',
      'Bossu',
      'Musclé',
      'Maigre',
      'Body buildé',
      'Fit',
      'Obèse',
      '',
    ],
  },
  {
    name: 'Coiffure',
    attributes: [
      'Chauve',
      'Cheveux longs',
      'Cheveux très longs',
      'Cheveux courts',
      'Calvicie',
    ],
  },
  {
    name: 'Particularité physique',
    attributes: [
      'Grosses dents',
      'Gros yeux',
      'Grosse lèvres',
      'Menton carré',
      'Pas de cou',
      'Manchot',
      'Œil crevé',
      'Gros nez',
      'Barbe',
      'Moustache',
      'Gros sourcils',
      'Poilu',
      'Tatouage',
      'Cicatrices',
    ],
  },
  {
    name: 'Caractère',
    attributes: [
      'Timide',
      'Fier',
      'Intello',
      'Idiot',
      'Colérique',
      'Triste',
      'Appeuré',
      'Courageux',
      'Énigmatique',
      'Fier',
      'Noble',
      'Rusé',
      'Fou',
    ],
  },
]
